# Generated by Django 3.1.3 on 2020-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvo',
            name='latitude',
            field=models.FloatField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='alvo',
            name='longitude',
            field=models.FloatField(verbose_name=10),
        ),
    ]
