# Generated by Django 3.1.3 on 2020-11-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201124_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvo',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alvo',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
